### ISSUE TITLE
Try keeping commented out code to a minimum

### ISSUE THREAD

**Issue by SidTheEngineer** [monkey-tree/jammming#3]
Throughout `App.js` and a couple other places there is a decent amount of commented out code. A commented out `console.log` here or there is usually okay, but sometimes leaving large chunks of commented out code in the components can cause some clutter and make the code a little bit more cumbersome to read through. It's usually best to simply remove the code and if you need to see it again in the future, use git to check out old commits and see where we might need the old code again.

**Comment by monkey-tree** [comment]
Removed the commented code.
